### ISSUE TITLE
Extension not working

### ISSUE THREAD

**Issue by skrichten** [mrmlnc/vscode-less#35]
This extension doesn't seem to be working at all for me.  Here are the errors I see...

At the time I was hovering over a variable that was imported from another less file.

C:\Program Files (x86)\Microsoft VS Code\resources\app\node_modules\vscode-textmate\release\main.js:2360 [4] - Grammar is in an endless loop - Grammar is not advancing, nor is it pushing/popping

shell.ts:437 Illegal argument, contents must be defined: Error: Illegal argument, contents must be defined
    at new e (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:11:7578)
    at asHover (C:\Users\SleekDigital\.vscode\extensions\mrmlnc.vscode-less-0.6.0\node_modules\vscode-languageclient\lib\protocolConverter.js:71:16)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by mrmlnc** [comment]
Hello,

Small question, you use VS Code 1.9.0?

**Comment by skrichten** [comment]
Yes

**Comment by mrmlnc** [comment]
Fixed in `master` branch. I'll create release very soon (today).

**Comment by skrichten** [comment]
Awesome, thanks!

**Comment by mrmlnc** [comment]
Should be fixed in `0.6.1`.
