### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by ayyash** [mrmlnc/vscode-less#50]
I know this is a stale plugin, but it was quite helpful for so long, this last month, it stopped working, I get no variable intellisense, any idea why?

**Comment by ayyash** [comment]
developer tools
```
  ERR Illegal argument, contents must be defined: Error: Illegal argument, contents must be defined
    at new e (c:\Users\elmot\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:409:909)
    at new e (c:\Users\elmot\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:398:174)
    at asHover (c:\Users\elmot\.vscode-insiders\extensions\mrmlnc.vscode-less-0.6.3\node_modules\vscode-languageclient\lib\protocolConverter.js:63:16)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

**Comment by ayyash** [comment]
hmmm, my last try that made it work again, is that if I reorganize the folder sort in the workspace, weird, it works in other workspaces but not this one, it probably is something wrong in one other folder
