### ISSUE TITLE
not work ant design less ?

### ISSUE THREAD

**Issue by jonlepage** [mrmlnc/vscode-less#51]
seem not working on my side 
![image](https://user-images.githubusercontent.com/24865815/79527233-0c86bc00-8035-11ea-8e2f-d0fdcefa7119.png)

```
[Error - 23 h 05 min 16 s] (node:17996) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null
    at makeMixinParameters (c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\node_modules\less-symbols-parser\out\index.js:15:23)
    at Object.parseSymbols (c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\node_modules\less-symbols-parser\out\index.js:162:33)
    at Object.findSymbols (c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\out\parser\symbols.js:12:34)
    at Object.parseDocument (c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\out\services\parser.js:20:29)
    at c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\out\services\scanner.js:23:38
[Error - 23 h 05 min 16 s] (node:17996) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null
    at makeMixinParameters (c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\node_modules\less-symbols-parser\out\index.js:15:23)
    at Object.parseSymbols (c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\node_modules\less-symbols-parser\out\index.js:162:33)
    at Object.findSymbols (c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\out\parser\symbols.js:12:34)
    at Object.parseDocument (c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\out\services\parser.js:20:29)
    at c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\out\services\scanner.js:23:38
[Error - 23 h 05 min 16 s] (node:17996) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[Error - 23 h 05 min 16 s] (node:17996) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[Error - 23 h 05 min 16 s] (node:17996) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[Error - 23 h 05 min 16 s] (node:17996) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[Error - 23 h 05 min 16 s] (node:17996) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null
    at makeMixinParameters (c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\node_modules\less-symbols-parser\out\index.js:15:23)
    at Object.parseSymbols (c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\node_modules\less-symbols-parser\out\index.js:162:33)
    at Object.findSymbols (c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\out\parser\symbols.js:12:34)
    at Object.parseDocument (c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\out\services\parser.js:20:29)
    at c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\out\services\scanner.js:23:38
[Error - 23 h 05 min 16 s] (node:17996) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null
    at makeMixinParameters (c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\node_modules\less-symbols-parser\out\index.js:15:23)
    at Object.parseSymbols (c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\node_modules\less-symbols-parser\out\index.js:162:33)
    at Object.findSymbols (c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\out\parser\symbols.js:12:34)
    at Object.parseDocument (c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\out\services\parser.js:20:29)
    at c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\out\services\scanner.js:23:38
[Error - 23 h 05 min 16 s] (node:17996) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
[Error - 23 h 05 min 16 s] (node:17996) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
[Error - 23 h 05 min 16 s] (node:17996) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null
    at makeMixinParameters (c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\node_modules\less-symbols-parser\out\index.js:15:23)
    at Object.parseSymbols (c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\node_modules\less-symbols-parser\out\index.js:162:33)
    at Object.findSymbols (c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\out\parser\symbols.js:12:34)
    at Object.parseDocument (c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\out\services\parser.js:20:29)
    at c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\out\services\scanner.js:23:38
[Error - 23 h 05 min 16 s] (node:17996) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null
    at makeMixinParameters (c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\node_modules\less-symbols-parser\out\index.js:15:23)
    at Object.parseSymbols (c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\node_modules\less-symbols-parser\out\index.js:162:33)
    at Object.findSymbols (c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\out\parser\symbols.js:12:34)
    at Object.parseDocument (c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\out\services\parser.js:20:29)
    at c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\out\services\scanner.js:23:38
[Error - 23 h 05 min 16 s] (node:17996) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
[Error - 23 h 05 min 16 s] (node:17996) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
[Error - 23 h 05 min 16 s] (node:17996) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null
    at makeMixinParameters (c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\node_modules\less-symbols-parser\out\index.js:15:23)
    at Object.parseSymbols (c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\node_modules\less-symbols-parser\out\index.js:162:33)
    at Object.findSymbols (c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\out\parser\symbols.js:12:34)
    at Object.parseDocument (c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\out\services\parser.js:20:29)
    at c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\out\services\scanner.js:23:38
[Error - 23 h 05 min 16 s] (node:17996) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null
    at makeMixinParameters (c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\node_modules\less-symbols-parser\out\index.js:15:23)
    at Object.parseSymbols (c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\node_modules\less-symbols-parser\out\index.js:162:33)
    at Object.findSymbols (c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\out\parser\symbols.js:12:34)
    at Object.parseDocument (c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\out\services\parser.js:20:29)
    at c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\out\services\scanner.js:23:38
[Error - 23 h 05 min 16 s] (node:17996) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
[Error - 23 h 05 min 16 s] (node:17996) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
[Error - 23 h 05 min 16 s] (node:17996) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null
    at makeMixinParameters (c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\node_modules\less-symbols-parser\out\index.js:15:23)
    at Object.parseSymbols (c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\node_modules\less-symbols-parser\out\index.js:162:33)
    at Object.findSymbols (c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\out\parser\symbols.js:12:34)
    at Object.parseDocument (c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\out\services\parser.js:20:29)
    at c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\out\services\scanner.js:23:38
[Error - 23 h 05 min 16 s] (node:17996) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null
    at makeMixinParameters (c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\node_modules\less-symbols-parser\out\index.js:15:23)
    at Object.parseSymbols (c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\node_modules\less-symbols-parser\out\index.js:162:33)
    at Object.findSymbols (c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\out\parser\symbols.js:12:34)
    at Object.parseDocument (c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\out\services\parser.js:20:29)
    at c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\out\services\scanner.js:23:38
[Error - 23 h 05 min 16 s] (node:17996) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
[Error - 23 h 05 min 16 s] (node:17996) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
[Error - 23 h 05 min 16 s] (node:17996) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null
    at makeMixinParameters (c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\node_modules\less-symbols-parser\out\index.js:15:23)
    at Object.parseSymbols (c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\node_modules\less-symbols-parser\out\index.js:162:33)
    at Object.findSymbols (c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\out\parser\symbols.js:12:34)
    at Object.parseDocument (c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\out\services\parser.js:20:29)
    at c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\out\services\scanner.js:23:38
[Error - 23 h 05 min 16 s] (node:17996) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null
    at makeMixinParameters (c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\node_modules\less-symbols-parser\out\index.js:15:23)
    at Object.parseSymbols (c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\node_modules\less-symbols-parser\out\index.js:162:33)
    at Object.findSymbols (c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\out\parser\symbols.js:12:34)
    at Object.parseDocument (c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\out\services\parser.js:20:29)
    at c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\out\services\scanner.js:23:38
[Error - 23 h 05 min 16 s] (node:17996) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
[Error - 23 h 05 min 16 s] (node:17996) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
[Error - 23 h 05 min 16 s] (node:17996) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null
    at makeMixinParameters (c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\node_modules\less-symbols-parser\out\index.js:15:23)
    at Object.parseSymbols (c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\node_modules\less-symbols-parser\out\index.js:162:33)
    at Object.findSymbols (c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\out\parser\symbols.js:12:34)
    at Object.parseDocument (c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\out\services\parser.js:20:29)
    at c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\out\services\scanner.js:23:38
[Error - 23 h 05 min 16 s] (node:17996) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null
    at makeMixinParameters (c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\node_modules\less-symbols-parser\out\index.js:15:23)
    at Object.parseSymbols (c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\node_modules\less-symbols-parser\out\index.js:162:33)
    at Object.findSymbols (c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\out\parser\symbols.js:12:34)
    at Object.parseDocument (c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\out\services\parser.js:20:29)
    at c:\Users\InformatiqueLepage\.vscode\extensions\mrmlnc.vscode-less-0.6.3\out\services\scanner.js:23:38
[Error - 23 h 05 min 16 s] (node:17996) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)
[Error - 23 h 05 min 16 s] (node:17996) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)
[vscode-less]: TypeError
[vscode-less]: TypeError: Cannot read property '1' of null
[Error - 23 h 05 min 16 s] (node:17996) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
[Error - 23 h 05 min 16 s] (node:17996) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
[Error - 23 h 05 min 16 s] (node:17996) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 2)
[Error - 23 h 05 min 16 s] (node:17996) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 2)
[Error - 23 h 05 min 16 s] (node:17996) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 3)
[Error - 23 h 05 min 16 s] (node:17996) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 3)
[Error - 23 h 05 min 16 s] (node:17996) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 4)
[Error - 23 h 05 min 16 s] (node:17996) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 4)
[Error - 23 h 05 min 16 s] (node:17996) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 5)
[Error - 23 h 05 min 16 s] (node:17996) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 5)
[Error - 23 h 05 min 16 s] (node:17996) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 6)
[Error - 23 h 05 min 16 s] (node:17996) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 6)
[Error - 23 h 05 min 16 s] (node:17996) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 7)
[Error - 23 h 05 min 16 s] (node:17996) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 7)
```

**Comment by kaysonwu** [comment]
@mrmlnc I have the same problem
